export const NEXT = {
  end: 'END',
  proceed: 'PROCEED',
  completed: 'COMPLETED',
};

export const QUESTIONS = [
  {
    questionId: 'q1',
    question: 'How many valid IDs do you have?',
    inputType: 'radio',
    points: 10,
    options: [
      {
        answerId: 'a1',
        nextQuestionId: null,
        next: NEXT.end,
        points: 0,
        answer: 'None',
        message: "Unfortunately, banks require at least 1-2 valid IDs (photo-bearing government-issued) for you to apply for a home loan. However, you may apply for valid IDs in various institutions such as the DFA (for Philippine passport), SSS (for UMID), PHLPost (for postal ID), PRC (for PRC ID if you're a practicing professional), LTO (for driver's license), COMELEC (for digitized voter's ID), and Bureau of Immigration (for ACR if you're a foreigner). If you're applying for an ID for the first time, you may want to prepare your birth certificate plus a secondary ID such as a company ID, NBI Clearance, Police Clearance, Barangay Certification, etc. so you can apply for a Postal ID (card type).",
        sortOrder: 1,
      },
      {
        answerId: 'a2',
        nextQuestionId: 'q8',
        next: NEXT.proceed,
        points: 6,
        answer: '1',
        message: 'Good! Some banks accept at least 1 valid ID but it would be better if you can get another valid ID so that your bank of choice won\'t be limited to a few (other banks require at least 2 valid IDs).',
        sortOrder: 2,
      },
      {
        answerId: 'a3',
        nextQuestionId: 'q8',
        next: NEXT.proceed,
        points: 15,
        answer: '2 or more',
        message: 'Great! With at least 2 valid IDs or more, you may have a wide variety of bank options to choose from.',
        sortOrder: 3,
      },
    ],
  },
  {
    questionId: 'q8',
    question: 'If you don\'t mind, what age group do you belong to?',
    inputType: 'radio',
    points: 10,
    options: [
      {
        answerId: 'a57',
        nextQuestionId: null,
        next: NEXT.end,
        points: 0,
        answer: 'below 21',
        message: "You're still too young! Most banks require a minimum age of 21 and maximum age of 65 to avail of a home loan.",
        sortOrder: 1,
      },
      {
        answerId: 'a58',
        nextQuestionId: 'q2',
        next: NEXT.proceed,
        points: 6,
        answer: '21-65',
        message: 'Great! You are perfectly within range of what most banks require in terms of age requirement.',
        sortOrder: 2,
      },
      {
        answerId: 'a59',
        nextQuestionId: 'q2',
        next: NEXT.proceed,
        points: 15,
        answer: '66 and up',
        message: 'Unfortunately, most banks require a minimum age of 21 and maximum age of 65 to avail of a home loan. If you can pay in cash and can present a proof of income, you can still purchase a property directly from a developer or owner.',
        sortOrder: 3,
      },
    ],
  },
  {
    questionId: 'q2',
    question: 'What is your civil status?',
    inputType: 'radio',
    points: 15,
    options: [
      {
        answerId: 'a4',
        nextQuestionId: 'q2q1',
        next: NEXT.proceed,
        points: 0,
        answer: 'Married',
        message: null,
        sortOrder: 1,
      },
      {
        answerId: 'a5',
        nextQuestionId: 'q2q2',
        next: NEXT.proceed,
        points: 0,
        answer: 'Divorced or Separated',
        message: null,
        sortOrder: 2,
      },
      {
        answerId: 'a6',
        nextQuestionId: 'q3',
        next: NEXT.proceed,
        points: 14,
        answer: 'Single',
        message: 'One of the pros of being single is a lesser requirement in terms of property purchase or home loan compared to married individuals. But also be prepared if some banks would require a Certificate of No Marriage (CENOMAR).',
        sortOrder: 3,
      },
    ],
  },
  {
    questionId: 'q2q1',
    question: 'Can you provide a marriage certificate?',
    inputType: 'radio',
    points: 15,
    options: [
      {
        answerId: 'a7',
        nextQuestionId: 'q3',
        next: NEXT.proceed,
        points: 14,
        answer: 'Yes',
        message: 'That\'s good if you can ready your marriage certificate if you want to proceed with a home loan evaluation as it\'s a requirement for married individuals.',
        sortOrder: 1,
      },
      {
        answerId: 'a8',
        nextQuestionId: 'q3',
        next: NEXT.proceed,
        points: 11,
        answer: 'No',
        message: 'You may have your reasons why you can\'t provide a marriage certificate even though you\'re married but please note that if you\'d like to include your spouse in the property contract and title, you\'d have to present one. Otherwise, your status will be single.',
        sortOrder: 2,
      },
    ],
  },
  {
    questionId: 'q2q2',
    question: 'Can you provide divorce papers or legal separation document?',
    inputType: 'radio',
    points: 15,
    options: [
      {
        answerId: 'a9',
        nextQuestionId: 'q3',
        next: NEXT.proceed,
        points: 14,
        answer: 'Yes',
        message: "That's good if you can ready your divorce papers or legal separation documents if you don’t want to include your partner from a previous message in the property title or home loan contract.",
        sortOrder: 1,
      },
      {
        answerId: 'a10',
        nextQuestionId: 'q3',
        next: NEXT.proceed,
        points: 11,
        answer: 'No',
        message: 'You may have your reasons why you can\'t provide divorce papers or legal separation documents. Please note however that there could be a conflict if the bank verifies that you\'re legally married even if you may be physically separated from a previous partner.',
        sortOrder: 2,
      },
    ],
  },
  {
    questionId: 'q3',
    question: 'What best describes your citizenship?',
    inputType: 'radio',
    points: 15,
    options: [
      {
        answerId: 'a11',
        nextQuestionId: 'q3q1',
        next: NEXT.proceed,
        points: 0,
        answer: 'Non-Filipino',
        message: null,
        sortOrder: 1,
      },
      {
        answerId: 'a12',
        nextQuestionId: 'q4',
        next: NEXT.proceed,
        points: 0,
        answer: 'Dual Citizen',
        message: 'Nice! Though some banks have the same requirements for a Dual Citizen as that of a Filipino, other banks may require an Oath of Allegiance from the Philippine Embassy so you may also want to prepare for that one soon.',
        sortOrder: 2,
      },
      {
        answerId: 'a13',
        nextQuestionId: 'q4',
        next: NEXT.proceed,
        points: 14,
        answer: 'Filipino',
        message: 'Ayos Kabayan! Malaya kang makakabili ng condo unit, bahay at lupa o di kaya\'y lupa lang.',
        sortOrder: 3,
      },
    ],
  },
  {
    questionId: 'q3q1',
    question: 'Do you work here in the Philippines?',
    inputType: 'radio',
    points: 15,
    options: [
      {
        answerId: 'a14',
        nextQuestionId: 'q4',
        next: NEXT.proceed,
        points: 14,
        answer: 'Yes',
        message: 'Great! It would be easier for you to procure documents required for a non-Filipino such as Alien Certificate of Registration, Special Resident Retiree\'s Visa, proof of residence, etc. if you work here.',
        sortOrder: 1,
      },
      {
        answerId: 'a15',
        nextQuestionId: null,
        next: NEXT.end,
        points: 0,
        answer: 'No',
        message: "Even if you don't work here but plans to stay for a long time or visit the Philippines regularly and wants to have your own residential property through a condo unit, you may still try to acquire an Alien Certificate of Registration or Special Resident Retiree's Visa (SRRV) and proof of residence so you may be potentially eligible to secure a home loan.",
        sortOrder: 2,
      },
    ],
  },
  {
    questionId: 'q4',
    question: 'What best describes your type of livelihood?',
    inputType: 'radio',
    points: 15,
    options: [
      {
        answerId: 'a16',
        nextQuestionId: 'q4q1',
        next: NEXT.proceed,
        points: 0,
        answer: 'OFW',
        message: null,
        sortOrder: 1,
      },
      {
        answerId: 'a17',
        nextQuestionId: 'q4q2',
        next: NEXT.proceed,
        points: 0,
        answer: 'Self-employed',
        message: null,
        sortOrder: 2,
      },
      {
        answerId: 'a18',
        nextQuestionId: 'q4q3',
        next: NEXT.proceed,
        points: 0,
        answer: 'Locally employed',
        message: null,
        sortOrder: 3,
      },
    ],
  },
  {
    questionId: 'q4q1',
    question: 'Which of these documents can you provide?',
    inputType: 'checkbox',
    points: 15,
    // OFW
    options: [
      {
        answerId: 'a19',
        nextQuestionId: 'q5',
        next: NEXT.proceed,
        points: 3,
        answer: 'Latest Certificate of Employment and Compensation',
        message: 'We encourage you to provide these documents as complete as you can (OR AS APPLICABLE) for the processing of your home loan that is required by most banks - Latest Certificate of Employment and Compensation, Latest Crew or POEA Contract, Latest Employment Contract, Allotment Slip, Latest Payslip or Bank Statement/Remittance. By sending as much of these documents as you can or as possible, the bank can trust you more and would increase your chances of passing its evalutation process.',
        sortOrder: 1,
      },
      {
        answerId: 'a20',
        nextQuestionId: 'q5',
        next: NEXT.proceed,
        points: 3,
        answer: 'Latest Crew or POEA Contract, if sea-based',
        message: 'We encourage you to provide these documents as complete as you can (OR AS APPLICABLE) for the processing of your home loan that is required by most banks - Latest Certificate of Employment and Compensation, Latest Crew or POEA Contract, Latest Employment Contract, Allotment Slip, Latest Payslip or Bank Statement/Remittance. By sending as much of these documents as you can or as possible, the bank can trust you more and would increase your chances of passing its evalutation process.',
        sortOrder: 2,
      },
      {
        answerId: 'a60',
        nextQuestionId: 'q5',
        next: NEXT.proceed,
        points: 3,
        answer: 'Latest Employment Contract',
        message: 'We encourage you to provide these documents as complete as you can (OR AS APPLICABLE) for the processing of your home loan that is required by most banks - Latest Certificate of Employment and Compensation, Latest Crew or POEA Contract, Latest Employment Contract, Allotment Slip, Latest Payslip or Bank Statement/Remittance. By sending as much of these documents as you can or as possible, the bank can trust you more and would increase your chances of passing its evalutation process.',
        sortOrder: 3,
      },
      {
        answerId: 'a21',
        nextQuestionId: 'q5',
        next: NEXT.proceed,
        points: 3,
        answer: 'Allotment Slip',
        message: 'We encourage you to provide these documents as complete as you can (OR AS APPLICABLE) for the processing of your home loan that is required by most banks - Latest Certificate of Employment and Compensation, Latest Crew or POEA Contract, Latest Employment Contract, Allotment Slip, Latest Payslip or Bank Statement/Remittance. By sending as much of these documents as you can or as possible, the bank can trust you more and would increase your chances of passing its evalutation process.',
        sortOrder: 4,
      },
      {
        answerId: 'a22',
        nextQuestionId: 'q5',
        next: NEXT.proceed,
        points: 3,
        answer: 'Latest Payslip or Bank Statement/Remittance',
        message: 'We encourage you to provide these documents as complete as you can (OR AS APPLICABLE) for the processing of your home loan that is required by most banks - Latest Certificate of Employment and Compensation, Latest Crew or POEA Contract, Latest Employment Contract, Allotment Slip, Latest Payslip or Bank Statement/Remittance. By sending as much of these documents as you can or as possible, the bank can trust you more and would increase your chances of passing its evalutation process.',
        sortOrder: 5,
      },
      {
        answerId: 'a23',
        nextQuestionId: null,
        next: NEXT.end,
        points: 0,
        answer: 'None of the above',
        message: 'Unfortunately, you need to provide proof of income to be able to apply for a home loan. Hopefully you can get one from your employer and bank of account.',
        sortOrder: 6,
      },
    ],
  },
  {
    questionId: 'q4q2',
    question: 'Which of these documents can you provide?',
    inputType: 'checkbox',
    points: 15,
    // Self-employed
    options: [
      {
        answerId: 'a24',
        nextQuestionId: 'q5',
        next: NEXT.proceed,
        points: 1.5,
        answer: 'Audited Financial Statements',
        message: 'We encourage you to provide these documents as complete as you can (OR AS APPLICABLE) for the processing of your home loan that is required by most banks - Audited Financial Statements, Bank Statements, Lease/Rental Contracts, Certificate of Business Registration with DTI or SEC, Business Background of Company Profile, Professional Information Sheet, List of Customers and Suppliers or Trade References, Board or Partnership Resolution / SEC Certificate, Articles of Incorporation and By-laws. By sending as much of these documents as you can or as possible, the bank can trust you more and would increase your chances of passing its evalutation process.',
        sortOrder: 1,
      },
      {
        answerId: 'a25',
        nextQuestionId: 'q5',
        next: NEXT.proceed,
        points: 1.5,
        answer: 'Bank Statements',
        message: 'We encourage you to provide these documents as complete as you can (OR AS APPLICABLE) for the processing of your home loan that is required by most banks - Audited Financial Statements, Bank Statements, Lease/Rental Contracts, Certificate of Business Registration with DTI or SEC, Business Background of Company Profile, Professional Information Sheet, List of Customers and Suppliers or Trade References, Board or Partnership Resolution / SEC Certificate, Articles of Incorporation and By-laws. By sending as much of these documents as you can or as possible, the bank can trust you more and would increase your chances of passing its evalutation process.',
        sortOrder: 2,
      },
      {
        answerId: 'a26',
        nextQuestionId: 'q5',
        next: NEXT.proceed,
        points: 1.5,
        answer: 'Lease/Rental Contracts',
        message: 'We encourage you to provide these documents as complete as you can (OR AS APPLICABLE) for the processing of your home loan that is required by most banks - Audited Financial Statements, Bank Statements, Lease/Rental Contracts, Certificate of Business Registration with DTI or SEC, Business Background of Company Profile, Professional Information Sheet, List of Customers and Suppliers or Trade References, Board or Partnership Resolution / SEC Certificate, Articles of Incorporation and By-laws. By sending as much of these documents as you can or as possible, the bank can trust you more and would increase your chances of passing its evalutation process.',
        sortOrder: 3,
      },
      {
        answerId: 'a27',
        nextQuestionId: 'q5',
        next: NEXT.proceed,
        points: 1.5,
        answer: 'Certificate of Business Registration w/ DTI or SEC',
        message: 'We encourage you to provide these documents as complete as you can (OR AS APPLICABLE) for the processing of your home loan that is required by most banks - Audited Financial Statements, Bank Statements, Lease/Rental Contracts, Certificate of Business Registration with DTI or SEC, Business Background of Company Profile, Professional Information Sheet, List of Customers and Suppliers or Trade References, Board or Partnership Resolution / SEC Certificate, Articles of Incorporation and By-laws. By sending as much of these documents as you can or as possible, the bank can trust you more and would increase your chances of passing its evalutation process.',
        sortOrder: 4,
      },
      {
        answerId: 'a28',
        nextQuestionId: 'q5',
        next: NEXT.proceed,
        points: 1.5,
        answer: 'Business Background or Company Profile',
        message: 'We encourage you to provide these documents as complete as you can (OR AS APPLICABLE) for the processing of your home loan that is required by most banks - Audited Financial Statements, Bank Statements, Lease/Rental Contracts, Certificate of Business Registration with DTI or SEC, Business Background of Company Profile, Professional Information Sheet, List of Customers and Suppliers or Trade References, Board or Partnership Resolution / SEC Certificate, Articles of Incorporation and By-laws. By sending as much of these documents as you can or as possible, the bank can trust you more and would increase your chances of passing its evalutation process.',
        sortOrder: 5,
      },
      {
        answerId: 'a29',
        nextQuestionId: 'q5',
        next: NEXT.proceed,
        points: 1.5,
        answer: 'Professional Information Sheet',
        message: 'We encourage you to provide these documents as complete as you can (OR AS APPLICABLE) for the processing of your home loan that is required by most banks - Audited Financial Statements, Bank Statements, Lease/Rental Contracts, Certificate of Business Registration with DTI or SEC, Business Background of Company Profile, Professional Information Sheet, List of Customers and Suppliers or Trade References, Board or Partnership Resolution / SEC Certificate, Articles of Incorporation and By-laws. By sending as much of these documents as you can or as possible, the bank can trust you more and would increase your chances of passing its evalutation process.',
        sortOrder: 6,
      },
      {
        answerId: 'a30',
        nextQuestionId: 'q5',
        next: NEXT.proceed,
        points: 1.5,
        answer: 'List of Customers and Suppliers/Trade References',
        message: 'We encourage you to provide these documents as complete as you can (OR AS APPLICABLE) for the processing of your home loan that is required by most banks - Audited Financial Statements, Bank Statements, Lease/Rental Contracts, Certificate of Business Registration with DTI or SEC, Business Background of Company Profile, Professional Information Sheet, List of Customers and Suppliers or Trade References, Board or Partnership Resolution / SEC Certificate, Articles of Incorporation and By-laws. By sending as much of these documents as you can or as possible, the bank can trust you more and would increase your chances of passing its evalutation process.',
        sortOrder: 7,
      },
      {
        answerId: 'a31',
        nextQuestionId: 'q5',
        next: NEXT.proceed,
        points: 1.5,
        answer: 'Board or Partnership Resolution/Sec Certificate',
        message: 'We encourage you to provide these documents as complete as you can (OR AS APPLICABLE) for the processing of your home loan that is required by most banks - Audited Financial Statements, Bank Statements, Lease/Rental Contracts, Certificate of Business Registration with DTI or SEC, Business Background of Company Profile, Professional Information Sheet, List of Customers and Suppliers or Trade References, Board or Partnership Resolution / SEC Certificate, Articles of Incorporation and By-laws. By sending as much of these documents as you can or as possible, the bank can trust you more and would increase your chances of passing its evalutation process.',
        sortOrder: 8,
      },
      {
        answerId: 'a32',
        nextQuestionId: 'q5',
        next: NEXT.proceed,
        points: 1.5,
        answer: 'Articles of Incorporations and By-Laws',
        message: 'We encourage you to provide these documents as complete as you can (OR AS APPLICABLE) for the processing of your home loan that is required by most banks - Audited Financial Statements, Bank Statements, Lease/Rental Contracts, Certificate of Business Registration with DTI or SEC, Business Background of Company Profile, Professional Information Sheet, List of Customers and Suppliers or Trade References, Board or Partnership Resolution / SEC Certificate, Articles of Incorporation and By-laws. By sending as much of these documents as you can or as possible, the bank can trust you more and would increase your chances of passing its evalutation process.',
        sortOrder: 9,
      },
      {
        answerId: 'a33',
        nextQuestionId: null,
        next: NEXT.end,
        points: 1.5,
        answer: 'None of the above',
        message: 'Unfortunately, you need to provide proof of income to be able to apply for a home loan. Hopefully you can get one from an applicable government institution and bank of account.',
        sortOrder: 10,
      },
    ],
  },
  {
    questionId: 'q4q3',
    question: 'Which of these documents can you provide?',
    inputType: 'checkbox',
    points: 15,
    // Locally employed
    options: [
      {
        answerId: 'a34',
        nextQuestionId: 'q5',
        next: NEXT.proceed,
        points: 3,
        answer: 'Latest Certificate of Employment and Compensation',
        message: 'We encourage you to provide these documents as complete as you can (OR AS APPLICABLE) for the processing of your home loan that is required by most banks - Latest Certificate of Employment and Compensatio, Latest Income Tax Return, Latest 3 Months Payslip, Latest Bank Statement for the last 6 months. By sending as much of these documents as you can or as possible, the bank can trust you more and would increase your chances of passing its evalutation process.',
        sortOrder: 1,
      },
      {
        answerId: 'a35',
        nextQuestionId: 'q5',
        next: NEXT.proceed,
        points: 3,
        answer: 'Latest Income Tax Return',
        message: 'We encourage you to provide these documents as complete as you can (OR AS APPLICABLE) for the processing of your home loan that is required by most banks - Latest Certificate of Employment and Compensatio, Latest Income Tax Return, Latest 3 Months Payslip, Latest Bank Statement for the last 6 months. By sending as much of these documents as you can or as possible, the bank can trust you more and would increase your chances of passing its evalutation process.',
        sortOrder: 2,
      },
      {
        answerId: 'a36',
        nextQuestionId: 'q5',
        next: NEXT.proceed,
        points: 3,
        answer: 'Latest 3 Months Payslip',
        message: 'We encourage you to provide these documents as complete as you can (OR AS APPLICABLE) for the processing of your home loan that is required by most banks - Latest Certificate of Employment and Compensatio, Latest Income Tax Return, Latest 3 Months Payslip, Latest Bank Statement for the last 6 months. By sending as much of these documents as you can or as possible, the bank can trust you more and would increase your chances of passing its evalutation process.',
        sortOrder: 3,
      },
      {
        answerId: 'a37',
        nextQuestionId: 'q5',
        next: NEXT.proceed,
        points: 3,
        answer: 'Latest Bank Statement for the last 6 months',
        message: 'We encourage you to provide these documents as complete as you can (OR AS APPLICABLE) for the processing of your home loan that is required by most banks - Latest Certificate of Employment and Compensatio, Latest Income Tax Return, Latest 3 Months Payslip, Latest Bank Statement for the last 6 months. By sending as much of these documents as you can or as possible, the bank can trust you more and would increase your chances of passing its evalutation process.',
        sortOrder: 3,
      },
      {
        answerId: 'a38',
        nextQuestionId: null,
        next: NEXT.end,
        points: 0,
        answer: 'None of the above',
        message: 'Unfortunately, you need to provide proof of income to be able to apply for a home loan. Hopefully you can get one from your employer and bank of account.',
        sortOrder: 4,
      },
    ],
  },
  {
    questionId: 'q5',
    question: 'As an individual, within what range does your monthly income fall (based on your basic salary with proof of income)?',
    inputType: 'radio',
    points: 15,
    options: [
      {
        answerId: 'a39',
        nextQuestionId: 'q5q1',
        next: NEXT.proceed,
        points: 3,
        answer: 'Php26,000 - 49,999.99',
        message: null,
        sortOrder: 1,
      },
      {
        answerId: 'a40',
        nextQuestionId: 'q6',
        next: NEXT.proceed,
        points: 8,
        answer: 'Php50,000 - 69,999.99',
        message: 'Nice. Most banks require a minimum basic salary of Php50,000 (combined or solo) as one of its requirements for a home loan application. But at this range, it\'s possible that you may be limited to socialized to affordable properties which is still good!',
        sortOrder: 2,
      },
      {
        answerId: 'a41',
        nextQuestionId: 'q6',
        next: NEXT.proceed,
        points: 12,
        answer: 'Php70,000 and above',
        message: 'Great! Most banks require a minimum basic salary of Php50,000 (combined or solo) as one of its requirements for a home loan application. At this income range, you may have a wide variety of property choices with regard to home loan.',
        sortOrder: 3,
      },
    ],
  },
  {
    questionId: 'q5q1',
    question: 'Do you have a spouse, sibling, parent, son/daughter or relative that has a regular monthly income via employment or business that you can assign as a co-borrower?',
    inputType: 'radio',
    points: 15,
    options: [
      {
        answerId: 'a44',
        nextQuestionId: null,
        next: NEXT.end,
        points: 0,
        answer: 'No',
        message: 'Unfortunately, most banks require a combined monthly income of Php50,000 as part of its home loan requirements. And if you can\'t have a co-borrower with a similar eligibility, it would be hard for you to get a home loan.',
        sortOrder: 1,
      },
      {
        answerId: 'a45',
        nextQuestionId: 'q5q1q1',
        next: NEXT.proceed,
        points: 0,
        answer: 'Yes',
        message: null,
        sortOrder: 2,
      },
    ],
  },
  {
    questionId: 'q5q1q1',
    question: "What's his/her monthly income (with proof of income) range?",
    inputType: 'radio',
    points: 15,
    options: [
      {
        answerId: 'a46',
        nextQuestionId: 'q6',
        next: NEXT.proceed,
        points: 0,
        answer: 'Php26,000 - 49,999.99',
        message: 'Nice. Most banks require a minimum basic salary of Php50,000 (combined or solo) as one of its requirements for a home loan application. So having a co-borrower with a monthly basic income that falls within this range may help increase your chances.',
        sortOrder: 1,
      },
      {
        answerId: 'a47',
        nextQuestionId: 'q6',
        next: NEXT.proceed,
        points: 0,
        answer: 'Php50,000 - 69,999.99',
        message: 'Good. Most banks require a minimum basic salary of Php50,000 (combined or solo) as one of its requirements for a home loan application. So having a co-borrower with a monthly basic income that falls within this range could increase your chances of getting a home loan.',
        sortOrder: 2,
      },
      {
        answerId: 'a48',
        nextQuestionId: 'q6',
        next: NEXT.proceed,
        points: 0,
        answer: 'Php70,000 and above',
        message: 'Great! Most banks require a minimum basic salary of Php50,000 (combined or solo) as one of its requirements for a home loan application. So having a co-borrower with a monthly basic income that falls within this range may enable you to get a home loan for a wide variety of property choices.',
        sortOrder: 3,
      },
    ],
  },
  {
    questionId: 'q6',
    question: 'How long have you stayed with your last company or been with your current company?',
    inputType: 'radio',
    points: 15,
    options: [
      {
        answerId: 'a51',
        nextQuestionId: 'q7',
        next: NEXT.proceed,
        points: 7,
        answer: 'Less than 2 years',
        message: 'Your tenure in a company is a factor that banks consider when evaluating a home loan application. At least 2 years is good but 3 years or more is preferable. However, you may also emphasize to the home loan representative if you\'ve had at least a 2-3 years stint with a previous company prior to your current or last one where you stayed (or are currently staying) for less than 2 years.',
        sortOrder: 1,
      },
      {
        answerId: 'a52',
        nextQuestionId: 'q7',
        next: NEXT.proceed,
        points: 12,
        answer: '2-3 years',
        message: 'That\'s nice! Some banks require a minimum of at least 2 years of continuous employment with a company. ',
        sortOrder: 2,
      },
      {
        answerId: 'a53',
        nextQuestionId: 'q7',
        next: NEXT.proceed,
        points: 14,
        answer: '3 years and above',
        message: 'Congrats on staying 3 years or more with your current company! This would increase your chances of passing a home loan evaluation provided that you also qualify on other factors. ',
        sortOrder: 3,
      },
    ],
  },
  {
    questionId: 'q7',
    question: 'Do you have unpaid loans or any kind or unpaid credit card balance in the past?',
    inputType: 'radio',
    points: 15,
    options: [
      {
        answerId: 'a54',
        nextQuestionId: null,
        next: NEXT.completed,
        points: 5,
        answer: 'Yes',
        message: 'It is ideal that you fully pay your unpaid loans first before getting a home loan. However, if your basic salary is is too high that it can accommodate 2 loans at the same time, then it\'s possible you can get approved for a home loan. We can refer you to home loan representatives about it.',
        sortOrder: 3,
      },
      {
        answerId: 'a55',
        nextQuestionId: null,
        next: NEXT.completed,
        points: 14,
        answer: 'No',
        message: 'That\'s great! Having an unpaid loan or credit card balance would be seen by banks as a bad indicator of one\'s capacity to fully pay and complete one\'s financial obligation and would affect your chances of passing a home loan evaluation.',
        sortOrder: 3,
      },
      {
        answerId: 'a56',
        nextQuestionId: null,
        next: NEXT.completed,
        points: 10,
        answer: 'Unsure',
        message: 'You may want to review if you have unpaid loans or credit card balance in the past as it can be seen by banks as a bad indicator of one\'s capacity to fully pay and complete a financial obligation and would affect your chances of passing a home loan evaluation.',
        sortOrder: 3,
      },
    ],
  },
];

export const noneOfTheAbove = ['a23', 'a33', 'a38'];
