/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:546a16be-915a-4106-ae6c-21517b655582",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_7OhNNjtVZ",
    "aws_user_pools_web_client_id": "5h2kij5oeen6t3beimt794gev3",
    "oauth": {
        "domain": "homeassistapp7448bc57-7448bc57-dev.auth.ap-southeast-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://dev.homeassistph.com/",
        "redirectSignOut": "https://dev.homeassistph.com/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
