/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_appsync_graphqlEndpoint": "https://uyyzkwy5z5dxnpu4lxpakvj7pm.appsync-api.ap-southeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-5bdb3e56bfgvjpnwilrp77swxi",
    "aws_cognito_identity_pool_id": "ap-southeast-1:3399fb17-bb86-4165-bd2b-23c230031b44",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_HZ9XlxFYA",
    "aws_user_pools_web_client_id": "5b1t5evjg2jhp8inqgesnb1cic",
    "oauth": {
        "domain": "homeassistappee97a109-ee97a109-dev.auth.ap-southeast-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
