/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:6af51835-9007-4918-b7e1-292fa2e743c9",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_PE8DMnzuv",
    "aws_user_pools_web_client_id": "391dh7qonc35sjttgoetklujvq",
    "oauth": {
        "domain": "homeassistphapp58f23a9b-58f23a9b-dev.auth.ap-southeast-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://dev.homeassistph.com/",
        "redirectSignOut": "https://dev.homeassistph.com/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cloud_logic_custom": [
        {
            "name": "mainhomeassistfunc",
            "endpoint": "https://nmkajrttqi.execute-api.ap-southeast-1.amazonaws.com/dev",
            "region": "ap-southeast-1"
        }
    ]
};


export default awsmobile;
